PIHOLE_INTERFACE=enp1s0
IPV4_ADDRESS=10.100.100.99/24
IPV6_ADDRESS=
INSTALL_WEB_INTERFACE=true
QUERY_LOGGING=true
DNS_FQDN_REQUIRED=true
DNS_BOGUS_PRIV=true
DNSSEC=true
REV_SERVER=true
WEBPASSWORD=85083f16a28cefdf49c9c2e17ef0974648b47c91f132afa06c7504faf9e33118
BLOCKING_ENABLED=true
DNSMASQ_LISTENING=all
REV_SERVER_CIDR=10.100.0.0/16
REV_SERVER_TARGET=10.100.100.1
REV_SERVER_DOMAIN=
PIHOLE_DNS_1=1.1.1.1
PIHOLE_DNS_2=1.0.0.1
PIHOLE_DNS_3=2606:4700:4700::1111
PIHOLE_DNS_4=2606:4700:4700::1001
